---
title: The ManyMoments Project
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: https://manymoments.github.io
baseurl: 
description: ManyMoments
navbar-links:
  About the project:
  - What is this project about: what is this project about
  - Our papers: ourpapers
  - Current data analysis: dataanalysis
  - Current data collection: datacollection
  - How to join the current data collection: howtojoin
  - Q&A: Q&A
  - Further information and documents: about-avishay
  Contact: videos
  News: start-here
  Literature: course
avatar: "/img/ManyMom.png"
navbar-col: "#BCD2EE"
navbar-text-col: "#00008B"
navbar-children-col: "#F0FFFF"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: ManyMoments project by Julia Moeller and Committee
social-network-links:
  email: manymoments@uni-leipzig.de
  twitter: 
  instagram:
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false
staticman:
  repository: 
  branch: 
  endpoint: 
  reCaptcha:
    siteKey: 
    secret: 
excerpt_length: 100
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 20
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-redirect-from
